### ISSUE TITLE
[Bug] Error with Pipenv on Windows 10

### ISSUE THREAD

**Issue by Austen-Suqi** [leon-ai/leon-cli#186]
**I tried to use Leon on Windows 10 and have an error with pipenv.**

**Leon check produces:**
 Error: Command failed with exit code 1: pipenv --version
'pipenv' is not recognized as an internal or external command,
operable program or batch file.
    at makeError (C:\Users\asuqi.leon\node_modules\execa\lib\error.js:59:11)
    at handlePromise (C:\Users\asuqi.leon\node_modules\execa\index.js:114:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 2)
    at C:\Users\asuqi.leon\scripts/check.js:43:6 {
  shortMessage: 'Command failed with exit code 1: pipenv --version',
  command: 'pipenv --version',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: "'pipenv' is not recognized as an internal or external command,\r\n" +
    'operable program or batch file.',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

**leon create birth also had the error:**
Error: Impossible to register Pipenv environment variables
For further information, look at the log file located at C:\Users\asuqi\AppData\Roaming@leon-ai\cli\Config\log-errors.txt

**The txt file shows:**
[leon create birth] Impossible to register Pipenv environment variables
LogError: Error while getting the path of python3 libraries

**Comment by Divlo** [comment]
Hey! @Austen-Suqi 
Thanks for your report, it is indeed a bug.

This should now be fixed.
Could you confirm that it works with the latest CLI version (v1.1.4)?
