### ISSUE TITLE
[Bug] Failed to Install Leon on Linux Mint 20.3

### ISSUE THREAD

**Issue by jvan1234** [leon-ai/leon-cli#189]
### Specs

- Leon version:
- OS (or browser) version: Linux Mint 20.3
- Node.js version: v18.7.0
- Complete "leon check" (or "npm run check") output:
`npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/joshua/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/joshua/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/joshua/.npm/_logs/2022-08-08T21_42_29_657Z-debug-0.log`
- (if using Docker) Complete "npm run docker:check" output:
- (optional) Leon skill version:

### Expected Behavior
When I run `leon create birth`, it should install without error.
### Actual Behavior
When I run `leon create birth`, it outputs:
`Error: Your package manager is not supported.
Supported: apk, apt, brew, pacman, yum.
For further information, look at the log file located at /home/joshua/.config/@leon-ai/cli/log-errors.txt`
APT is my Operating System's main package manager, I am uncertain why this is.
### How Do We Reproduce?
Uncertain.
### Extra (like a sample repo to reproduce the issue, etc.)
[log-errors.txt](https://github.com/leon-ai/leon/files/9285193/log-errors.txt)

**Comment by Divlo** [comment]
Hey! @jvan1234 
Thanks for your report.

I'm not able to reproduce, without a clear step-by-step explication to reproduce the bug, we can help, thanks for your understanding, hopefully, you will still be able to install and use Leon. :smile:

**Comment by thomasleveil** [comment]
Same error here with leon - 1.3.1

```
leon create birth
Error: Your package manager is not supported.
Supported: apk, apt, brew, dnf, pacman, yum.
```

```
cat /etc/*release*
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=21.1
DISTRIB_CODENAME=vera
DISTRIB_DESCRIPTION="Linux Mint 21.1 Vera"
NAME="Linux Mint"
VERSION="21.1 (Vera)"
ID=linuxmint
ID_LIKE="ubuntu debian"
PRETTY_NAME="Linux Mint 21.1"
VERSION_ID="21.1"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=vera
UBUNTU_CODENAME=jammy
```

**Comment by Divlo** [comment]
Hello! @thomasleveil 
Can you try like this:

```sh
npm install --global @leon-ai/cli@beta
leon create birth --develop
```

**Comment by thomasleveil** [comment]
> ```shell
> leon create birth --develop
> ```

It worked :tada: 

<details><summary>leon create birth --develop</summary>

```
✔ Downloading Leon source code
✔ Installing npm dependencies

> leon@1.0.0-beta.8+dev postinstall
> ts-node scripts/setup/setup.js

ℹ️  .env file creation...
✅ .env file created
ℹ️  Configuring core...
✅ google-drive.json file created
✅ amazon.json file created
✅ google-cloud.json file created
✅ watson-stt.json file created
✅ watson-tts.json file created
ℹ️  Setting up skills configuration...
✅ "Akinator" skill configuration file created
✅ "Guess the Number" skill configuration file created
✅ "Rochambeau" skill configuration file created
✅ "Greeting" skill configuration file created
✅ "Introduction" skill configuration file created
✅ "Random Number" skill configuration file created
✅ "GitHub Trends" skill configuration file created
✅ "Product Hunt Trends" skill configuration file created
✅ "Todo List" skill configuration file created
✅ "MBTI (Myers–Briggs Type Indicator)" skill configuration file created
✅ "Have I Been Pwned" skill configuration file created
✅ "Is It Down" skill configuration file created
✅ "Speed Test" skill configuration file created
✅ "YouTube Downloader" skill configuration file created
✅ Skills configured
ℹ️  Downloading Python bridge...
Download progress: 100% (13.3 MB/13.3 MB | 13.5 MB/s | 0 ETA)
✅ Python bridge downloaded
ℹ️  Extracting Python bridge...
✅ Python bridge extracted
✅ Python bridge ready
ℹ️  Downloading TCP server...
✔ Building Leon core

Success: Leon is born! 🎉
You can start your leon instance:
leon start
```

<details>
