### ISSUE TITLE
[Bug] Conflicting virtualenv version

### ISSUE THREAD

**Issue by pySec710** [leon-ai/leon-cli#190]
## Steps To Reproduce

1. have a conflicting version of virtualenv already installed on the computer
2. install leon

## The current behavior
  The bug is first noticed from initially sending a message to Leon and you get the reply:
 "Sorry, I've got an error with the "Greeting" module of my "Leon" package!".  

The CLI error states:
 ".: LEON :.
✖ 'pipenv' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\maria\.leon\server\dist\core\brain.js:243
            obj: new Error(data),
                 ^

Error: 'pipenv' is not recognized as an internal or external command,
operable program or batch file.

    at Socket.<anonymous> (C:\Users\maria\.leon\server\dist\core\brain.js:243:18)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
Error: Command failed with exit code 1: npm start"

## The expected behavior
leon should respond "Hello There!"

**Comment by pySec710** [comment]
To fix the bug I just uninstalled pipenv and virtualenv then reinstalled pipenv. I would recommend checking the system for other virtualenv versions on install. If found simply removing the package before install fixes it (and installing pipenv installs virtualenv as a dependency so the end user still has its virtualenv projects functional).

**Comment by Divlo** [comment]
Hey! @pySec710 
Thanks for your report!

Closing, as this seems to be resolved, please reopen if the issue still persists.
