### ISSUE TITLE
[Bug] Error creating with `fnm`

### ISSUE THREAD

**Issue by marclundgren** [leon-ai/leon-cli#192]
### Specs

- Leon version:
- OS (or browser) version: Mac Monterey 12.5.1 (m1)
- Node.js version: 14.20.0 (fnm)
- Complete "leon check" (or "npm run check") output:
- (if using Docker) Complete "npm run docker:check" output:
- (optional) Leon skill version:

### How Do We Reproduce?
```
leon create birth

✖ Installing packages
Error: Failed to install needed packages
For further information, look at the log file located at /Users/marc/Library/Preferences/@leon-ai/cli/log-errors.txt
```

viewing error logs
```
cat /Users/marc/Library/Preferences/@leon-ai/cli/log-errors.txt
[Sun Sep 04 2022 13:34:52 GMT-0700 (Pacific Daylight Time)] [leon create birth] Failed to install needed packages
Error: Command failed with ENOENT: /Users/marc/Library/Application Support/fnm/node-versions/v14.20.0/installation/lib/node_modules/@leon-ai/cli/scripts/dependencies/install_brew_packages.sh
spawn /Users/marc/Library/Application ENOENT
```

fnm lives at `/Users/marc/Library/Application Support` on a mac, and it looks like you're trying to spawn a process at `/Users/marc/Library/Application`, which is not a directory. Seems like a pathing bug to me

**Comment by louistiti** [comment]
Hi @marclundgren, you need a Node.js version of at least `16` as mentioned in [the prerequisites](https://github.com/leon-ai/leon#prerequisites).

Transferring this issue to the Leon CLI repo.

**Comment by Divlo** [comment]
Hello @marclundgren! :wave:

Thanks for your report, as Louis said, please install a newer version of Node.js.

I'm not familiar with `fnm`, as long as you're able to install Node.js with npm and globally install npm dependencies, it should work.

Yes, it is correct, we're spawning a process to install `brew` packages to then install Python v3.9.10, you can see the script source code in `scripts/dependencies/install_brew_packages.sh`.

**Comment by Divlo** [comment]
Closing as this should not be a issue for `leon-cli`, probably something related to `fnm`or something else.
Please reopen if you think this is a mistake.
