### ISSUE TITLE
[Bug] uncognized option --yes for archlinux

### ISSUE THREAD

**Issue by kamaradclimber** [leon-ai/leon-cli#193]
## Steps To Reproduce

1. run `leon create birth`

## The current behavior

On stdout: ```
✖ Installing packages
Error: Failed to install needed packages
For further information, look at the log file located at /home/me/.config/@leon-ai/cli/log-errors.txt
```

when looking at error files:
```
Error: Command failed with exit code 1: sudo --non-interactive /ssd/home/me/.npm-global/lib/node_modules/@leon-ai/cli/scripts/dependencies/install_pacman_packages.sh
pacman: unrecognized option '--yes'
```

## The expected behavior

correct installation

**Comment by Divlo** [comment]
Hello! @kamaradclimber

Thanks for your report!
Indeed it is a bug, actually `--yes` doesn't exist for the `pacman` CLI.

In the CLI part, we already support many famous package managers for different GNU/Linux distributions, but unfortunately, on the Core side, it is not the case.
Being able to run Leon on multiple CPU architectures, and distribution, it's definitely something we would like to support, and we would like to solve it before the v1.0.0 stable release (currently Leon is in **beta**).
We will try to solve this problem later, when the core of Leon is more mature, just before the v1 stable release.
You can read more here: https://github.com/leon-ai/leon/pull/302#pullrequestreview-914081908.

Meanwhile, you can use Leon without problems on Ubuntu, macOS, and Windows, also you can try Leon with a single click thanks to GitPod: https://github.com/leon-ai/leon#%EF%B8%8F-try-with-a-single-click.
