### ISSUE TITLE
leon start birth failed

### ISSUE THREAD

**Issue by Hkmu** [leon-ai/leon-cli#195]
## Steps To Reproduce

1. Step 1
Just run `leon create birth` on CentOS

## The current behavior

Error summary from log file `~/.config/@leon-ai/cli/log-errors.txt`:
```
Error: Command failed with exit code 2: sudo --non-interactive /root/.nvm/versions/node/v18.5.0/lib/node_modules/@leon-ai/cli/scripts/dependencies/install_yum_packages.sh

yum install: error: unrecognized arguments: --yes
```

## The expected behavior
`leon start birth` gets executed successfully.

**Comment by Divlo** [comment]
Hello! @Hkmu

Thanks for your report!
Indeed it is a bug, actually `--yes` doesn't exist for the `yum` CLI.

In the CLI part, we already support many famous package managers for different GNU/Linux distributions, but unfortunately, on the Core side, it is not the case.
Being able to run Leon on multiple CPU architectures, and distribution, it's definitely something we would like to support, and we would like to solve it before the v1.0.0 stable release (currently Leon is in **beta**).
We will try to solve this problem later, when the core of Leon is more mature, just before the v1 stable release.
You can read more here: https://github.com/leon-ai/leon/pull/302#pullrequestreview-914081908.

Meanwhile, you can use Leon without problems on Ubuntu, macOS, and Windows, also you can try Leon with a single click thanks to GitPod: https://github.com/leon-ai/leon#%EF%B8%8F-try-with-a-single-click.
