### ISSUE TITLE
[Bug] Pipenv missing, causing TCP server connection error

### ISSUE THREAD

**Issue by brhaka** [leon-ai/leon-cli#198]
When starting leon, everything works fine until it tries to connect to the TCP server. This step fails because Pipenv is missing.
`leon create birth` works fine and without errors.
I'm running it on a M1 Macbook.
Docker version also fails.

Leon version: beta7

`leon check` output: https://pastebin.com/TrY3Km4j
`leon create birth` output: https://pastebin.com/DZZKR0CP

## Steps To Reproduce
1. `leon create birth`
3. `leon start`

## The current behavior
TCP server connection fails, so leon doesn't work.

**Comment by Divlo** [comment]
For tracking purposes, I copy/paste what I posted on Discord, here on GitHub:
> The Docker version also fails for the same reason.
>
> It might fail because of the M1 CPU architecture, not everything supports it yet, if it is indeed the reason, I'm not sure what tool/dependency is incompatible with this CPU architecture.

---

Until further explanation or steps to reproduce the issue, the issue needs information (label added).

**Comment by brhaka** [comment]
Since the Docker version also fails, doesn't that imply that it's not the M1 architecture? Assuming the Docker is running on x86
